### Difference between an array and a vector

Vectors are always one dimensional like a single row of data. On the other hand, an array can be multidimensional (stored as rows and columns).


In [22]:
movie_vector<-c(2004,2005,2008)

In [23]:
movie_vector

[1] 2004 2005 2008

In [24]:
class(movie_vector)

[1] "numeric"

In [25]:
typeof(movie_vector)

[1] "double"

In [26]:
# Movie Vector is a Vector
# Convert it to an array

In [27]:
movie_array<-array(movie_vector)

In [28]:
movie_array

[1] 2004 2005 2008

In [29]:
typeof(movie_array)

[1] "double"

In [30]:
class(movie_array)

[1] "array"

In [31]:

movie_vector <- c("Akira", "Toy Story", "Room", "The Wave", "Whiplash",
                  "Star Wars", "The Ring", "The Artist", "Jumanji")
movie_vector

[1] "Akira"      "Toy Story"  "Room"       "The Wave"   "Whiplash"  
[6] "Star Wars"  "The Ring"   "The Artist" "Jumanji"

In [32]:
movie_array <- array(movie_vector, dim = c(4,3))
movie_array

[,1]      [,2]       [,3]     
[1,] Akira     Whiplash   Jumanji  
[2,] Toy Story Star Wars  Akira    
[3,] Room      The Ring   Toy Story
[4,] The Wave  The Artist Room

In [33]:
movie_array[1,2]   #[row, column]

[1] "Whiplash"

In [34]:
movie_array[1,]

[1] "Akira"    "Whiplash" "Jumanji"

In [35]:
movie_array[2,]

[1] "Toy Story" "Star Wars" "Akira"

In [36]:
movie_array[,2]

[1] "Whiplash"   "Star Wars"  "The Ring"   "The Artist"

In [37]:
# Dimention

In [38]:
dim(movie_array)

[1] 4 3

### Operations

In [39]:
a <- c(125, 81, 118, 81, 106, 121, 95, 100, 104)
a <- array(length_vector, dim = c(3,3))
a

ERROR: Error in array(length_vector, dim = c(3, 3)): object 'length_vector' not found


In [ ]:
a+2

In [ ]:
a*2

In [ ]:
a

In [ ]:
res=a**2

In [ ]:
res

In [ ]:
a

In [ ]:
a>120

In [ ]:
a<120

In [ ]:
a!=120

In [ ]:
a==120

In [ ]:
mask_array <- a > 120
mask_array

In [40]:
x_vector <- c("Akira", "Toy Story", "Room", "The Wave", "Whiplash",
              "Star Wars", "The Ring", "The Artist", "Jumanji")

x_array <- array(x_vector, dim = c(3,3))

x_array

x_array[mask_array]

[,1]      [,2]      [,3]      
[1,] Akira     The Wave  The Ring  
[2,] Toy Story Whiplash  The Artist
[3,] Room      Star Wars Jumanji

ERROR: Error in eval(expr, envir, enclos): object 'mask_array' not found


### Matrix

Matrices are a subtype of arrays. A matrix **must** have 2 dimensions, whereas arrays are more flexible and can have, 1, 2 or more dimensions.  

To create a matrix out of a vector , you can use **matrix()**, which takes in an argument for the vector, an argument for the number of rows and another for the number of columns.

In [41]:
movie_vector

[1] "Akira"      "Toy Story"  "Room"       "The Wave"   "Whiplash"  
[6] "Star Wars"  "The Ring"   "The Artist" "Jumanji"

In [42]:
movie_matrix<-matrix(movie_vector, nrow=3, ncol=3)

In [43]:
movie_matrix

[,1]      [,2]      [,3]      
[1,] Akira     The Wave  The Ring  
[2,] Toy Story Whiplash  The Artist
[3,] Room      Star Wars Jumanji

In [44]:
typeof(movie_matrix)

[1] "character"

In [45]:
class(movie_matrix)

[1] "matrix"

In [46]:
movie_matrix[1,2]

[1] "The Wave"

In [47]:
movie_matrix[1,1]

[1] "Akira"

In [48]:
movie_matrix[1,]  # FirstRow

[1] "Akira"    "The Wave" "The Ring"

In [49]:
movie_matrix[2,]   # Second Row

[1] "Toy Story"  "Whiplash"   "The Artist"

In [50]:
movie_matrix[,1]  # First Col

[1] "Akira"     "Toy Story" "Room"

In [51]:
movie_matrix[,2]  # Second Column

[1] "The Wave"  "Whiplash"  "Star Wars"

In [52]:
movie_matrix

[,1]      [,2]      [,3]      
[1,] Akira     The Wave  The Ring  
[2,] Toy Story Whiplash  The Artist
[3,] Room      Star Wars Jumanji

In [53]:
movie_matrix[1:3, 2:3]

[,1]      [,2]      
[1,] The Wave  The Ring  
[2,] Whiplash  The Artist
[3,] Star Wars Jumanji

In [54]:
movie_matrix[2:3, 1:2]

[,1]      [,2]     
[1,] Toy Story Whiplash 
[2,] Room      Star Wars